### ISSUE TITLE
No support for Azure OpenAI

### ISSUE THREAD

**Issue by Marvin-Vitcu** [victordibia/llmx#1]
Hello Victor :)

I really like what you are doing and want to use the recently released lida library for projects in my organization.
However, my organization uses Azure OpenAI.
For this we need to be able to specfiy three openai properties: 
 - openai.api_type
 - openai.api_base
 - openai.version

Here is an example authorization for an Azure OpenAI instance:

```
import openai
openai.api_type = "azure"
openai.api_base = "https://yourendpoint.openai.azure.com/"
openai.api_version = "2023-07-01-preview"
openai.api_key = os.getenv("OPENAI_API_KEY")
```

Can you please add these properties to llmx so it is possible to use lida?

Best regards
Marvin

**Comment by victordibia** [comment]
Hey Marvin,

Thanks for the note. 
I started a [pr](https://github.com/victordibia/llmx/commit/f2e6d3c8477492320d9af1d076c8388e6f7074f1).

Will merge once I get a chance to test behaviors in more detail. 

-V.

**Comment by victordibia** [comment]
Support for azure OAI is now implemented. 

Example usage is 

```python
azure_openai_gen = llm(
    provider="openai",
    api_type="azure",
    api_base=os.environ["AZURE_OPENAI_BASE"],
    api_key=os.environ["AZURE_OPENAI_API_KEY"],
    api_version="2023-07-01-preview",
)
openai_config = TextGenerationConfig(model="gpt-35-turbo-v0301", use_cache=True)
openai_response = azure_openai_gen.generate(messages, config=openai_config)
print(openai_response.text[0].content)
```

**Comment by victordibia** [comment]
Hey Ishaan,

Your library is great and does way more stuff than llmx is trying to do at the moment.
Thanks for sharing it, as I did not know about it previously! 

In terms of the current issue, this is already implemented in llmx.

V.

**Comment by krrishdholakia** [comment]
@victordibia why do you feel like it does more than you need?

**Comment by nuaabuaa07** [comment]
> Support for azure OAI is now implemented.
> 
> Example usage is
> 
> ```python
> azure_openai_gen = llm(
>     provider="openai",
>     api_type="azure",
>     api_base=os.environ["AZURE_OPENAI_BASE"],
>     api_key=os.environ["AZURE_OPENAI_API_KEY"],
>     api_version="2023-07-01-preview",
> )
> openai_config = TextGenerationConfig(model="gpt-35-turbo-v0301", use_cache=True)
> openai_response = azure_openai_gen.generate(messages, config=openai_config)
> print(openai_response.text[0].content)
> ```

I try to connect to my Azure endpoint ,by the mothod above but get error 。I try to test my url ,resourcename  by rest request and It is ok .Is there some mistake in my code?
<img width="1383" alt="image" src="https://github.com/victordibia/llmx/assets/25834421/c69bd49a-a3ae-4ea6-a3c3-d1266c8a7800">

**Comment by nuaabuaa07** [comment]
> > Support for azure OAI is now implemented.
> > Example usage is
> > ```python
> > azure_openai_gen = llm(
> >     provider="openai",
> >     api_type="azure",
> >     api_base=os.environ["AZURE_OPENAI_BASE"],
> >     api_key=os.environ["AZURE_OPENAI_API_KEY"],
> >     api_version="2023-07-01-preview",
> > )
> > openai_config = TextGenerationConfig(model="gpt-35-turbo-v0301", use_cache=True)
> > openai_response = azure_openai_gen.generate(messages, config=openai_config)
> > print(openai_response.text[0].content)
> > ```
> 
> I try to connect to my Azure endpoint ,by the mothod above but get error 。I try to test my url ,resourcename by rest request and It is ok .Is there some mistake in my code? <img alt="image" width="1383" src="https://user-images.githubusercontent.com/25834421/283053306-c69bd49a-a3ae-4ea6-a3c3-d1266c8a7800.png">

I finally know that if I want to use Azure , the "model"  params in TextGenerationConfig must be my "deployment_name" in Azure.
