### ISSUE TITLE
Please add support for Makersuite PALM api

### ISSUE THREAD

**Issue by sumukhakaparthi** [victordibia/llmx#4]
Hi, 
could you please add support for Makersuite PALM API (https://makersuite.google.com/)? 
Thank you for previously adding support for Vertex AI PALM API.

Thanks in advance

**Comment by victordibia** [comment]
Great idea, will raise a PR once I have an update

**Comment by victordibia** [comment]
Added support for Makersuite.
Give it a try!

```python 
palm_gen = llm(
    provider="palm",
    api_key=os.environ["PALM_API_KEY"],
)
palm_config = TextGenerationConfig(
    model="chat-bison-001", temperature=0, use_cache=True
)
palm_response = palm_gen.generate(messages, config=palm_config)
print(palm_response.text[0].content)

```
